name: Terraform Flow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Lint, Security Check, and Apply
    runs-on: ubuntu-latest

    env:
      GCP_REGION: 'us-east1'
      TF_VERSION: '1.5.4'
      TFLINT_VERSION: '0.53.0'
      TFSEC_VERSION: '1.28.11'
      TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}
      PROJECT_ID: 'ecstatic-valve-440419-a4'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create function bundle
        run: |
          mkdir -p bundle
          cd cloud_function/dataset_upload_function
          pip install -r requirements.txt -t .
          zip -r ../../bundle/dataset_upload_function.zip .

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Install the gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          export_default_credentials: true
          version: '>= 363.0.0'

      - name: Use gcloud CLI
        run: gcloud info

      - name: Authenticate with Google Cloud Platform
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Install TFLint
        run: |
          curl -sLo tflint.zip https://github.com/terraform-linters/tflint/releases/download/v${{ env.TFLINT_VERSION }}/tflint_linux_amd64.zip
          unzip tflint.zip -d /usr/local/bin/
          tflint --version

      - name: Install tfsec
        run: |
          curl -sLo tfsec https://github.com/aquasecurity/tfsec/releases/download/v${{ env.TFSEC_VERSION }}/tfsec-linux-amd64
          chmod +x tfsec
          mv tfsec /usr/local/bin/
          tfsec --version

      - name: Terraform Init
        run: (cd terraform && terraform init)

      - name: Terraform Format
        run: (cd terraform && terraform fmt)

      - name: Terraform Validate
        run: (cd terraform && terraform validate)

      - name: TFLint
        run: |
          tflint --init
          tflint

      - name: tfsec
        run: tfsec .

      - name: Terraform Plan
        run: (cd terraform && terraform plan --var-file=tfvars/common.tfvars -out=tfplan)

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: (cd terraform && terraform apply -auto-approve tfplan)

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
           credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
